# Generated by Django 5.2.1 on 2025-06-20 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_alter_price_options_remove_clientproject_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
