# Generated by Django 5.2.1 on 2025-06-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_jobtemplate_templateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workentry',
            name='category',
        ),
        migrations.AddField(
            model_name='workentry',
            name='template_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Invoice.templateitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workentry',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Invoice.clientproject'),
            preserve_default=False,
        ),
    ]
