# Generated by Django 5.2.1 on 2025-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_remove_workentry_category_workentry_template_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='default_quantity',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='description',
        ),
        migrations.AddField(
            model_name='templateitem',
            name='item_type_name',
            field=models.CharField(default=1, help_text="e.g., 'Clipping Path', 'Color Correction'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workentry',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
