# Generated by Django 5.2.1 on 2025-06-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0007_remove_templateitem_default_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='workentry',
            name='template_item',
        ),
        migrations.RemoveField(
            model_name='workentry',
            name='description',
        ),
        migrations.AddField(
            model_name='workentry',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.clientproject'),
        ),
        migrations.DeleteModel(
            name='JobTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
    ]
